import { Document, Packer, Paragraph, TextRun } from "docx";
import { saveAs } from "file-saver";

// Universal disclaimer (global, NOT local/Korean law)
const disclaimer =
  "This document is automatically generated by AI for reference purposes only. It does not constitute legal advice or a substitute for consultation with a qualified attorney.\n" +
  "No personal data or uploaded files are stored or shared. The user is fully responsible for all outcomes.\n" +
  "For case-specific interpretation, compliance, or legal action, consult with a licensed legal expert in your jurisdiction.";

export async function downloadLegalReportDOCX(report: string, fileName = "Lawrithm_Report.docx") {
  const lines = report.split(/\r?\n/);

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          ...lines.map(
            (line) =>
              new Paragraph({
                children: [new TextRun({ text: line })],
                spacing: { after: 150 },
              })
          ),
          new Paragraph({ text: "", spacing: { after: 200 } }),
          ...disclaimer.split(/\r?\n/).map(
            (line) =>
              new Paragraph({
                children: [
                  new TextRun({
                    text: line,
                    size: 16,
                    color: "777777",
                  }),
                ],
                spacing: { after: 60 },
              })
          ),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, fileName);
}
